version: '3.2'
services:
    las:
        image: registry.scontain.com:5050/sconecuratedimages/kubernetes:las-scone5.3.0
        devices:
         - "${SGXDEVICE}"
    build_and_sconify:
        image: ${SCONIFY_IMAGE}
        command: bash -c "/helper_scripts/alpine_wait_for_las_and_cas.sh && /sconification/sconify_all.sh"
        volumes:
            - ./sconification:/sconification
            - ./images:/images
            - ./helper_scripts:/helper_scripts
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - SWITCH_C=$SWITCH_C
            - SWITCH_CPP=$SWITCH_CPP
            - SWITCH_GO=$SWITCH_GO
            - SWITCH_JAVA11=$SWITCH_JAVA11
            - SWITCH_JAVA8=$SWITCH_JAVA8
            - SWITCH_PYTHON=$SWITCH_PYTHON
            - SWITCH_NODE=$SWITCH_NODE
            - SWITCH_DEBUG=$SWITCH_DEBUG
            - SWITCH_VERBOSE=$SWITCH_VERBOSE
        depends_on:
            - las
    c_native:
        image: ${C_NATIVE_IMAGE}
    c_scone_binaryfs:
        image: ${C_TARGET_IMAGE}
        environment:
         - SCONE_VERSION=1
        devices:
         - "${SGXDEVICE}"
        depends_on:
            - las
    cpp_native:
        image: ${CPP_NATIVE_IMAGE}
    cpp_scone_binaryfs:
        image: ${CPP_TARGET_IMAGE}
        environment:
         - SCONE_VERSION=1
        devices:
         - "${SGXDEVICE}"
        depends_on:
            - las
    go_native:
        image: ${GO_NATIVE_IMAGE}
    go_scone_fspf:
        image: ${GO_TARGET_IMAGE_FSPF}
        environment:
         - SCONE_VERSION=1
        devices:
         - "${SGXDEVICE}"
        depends_on:
            - las
    java_native:
        image: ${JAVA_NATIVE_IMAGE}
    java_scone_fspf:
        image: ${JAVA_TARGET_IMAGE_FSPF}
        environment:
         - SCONE_VERSION=1
        devices:
         - "${SGXDEVICE}"
        depends_on:
            - las
    java_scone_binaryfs:
        image: ${JAVA_TARGET_IMAGE_BINARYFS}
        environment:
         - SCONE_VERSION=1
        devices:
         - "${SGXDEVICE}"
        depends_on:
            - las
    java8_native:
        image: ${JAVA8_NATIVE_IMAGE}
    java8_scone_fspf:
        image: ${JAVA8_TARGET_IMAGE_FSPF}
        environment:
         - SCONE_VERSION=1
        devices:
         - "${SGXDEVICE}"
        depends_on:
            - las
    java8_scone_binaryfs:
        image: ${JAVA8_TARGET_IMAGE_BINARYFS}
        environment:
         - SCONE_VERSION=1
        devices:
         - "${SGXDEVICE}"
        depends_on:
            - las
    python_native:
        image: ${PYTHON_NATIVE_IMAGE}
    python_scone_binfs:
        image: ${PYTHON_TARGET_IMAGE_BINFS}
        environment:
         - SCONE_VERSION=1
        devices:
         - "${SGXDEVICE}"
        depends_on:
            - las
    node_native:
        image: ${NODE_NATIVE_IMAGE}
    node_scone_binfs:
        image: ${NODE_TARGET_IMAGE_BINFS}
        environment:
         - SCONE_VERSION=1
        devices:
         - "${SGXDEVICE}"
        depends_on:
            - las
