version: '3.2'
services:
    las:
        image: registry.scontain.com:5050/sconecuratedimages/services:las-scone5.3.0
        devices:
         - "${SGXDEVICE}"
    cas:
        image: registry.scontain.com:5050/sconecuratedimages/services:cas.preprovisioned-scone5.3.0
        devices:
         - "${SGXDEVICE}"
        depends_on:
         - las
    cas_mrenclave_generator:
        image: registry.scontain.com:5050/sconecuratedimages/services:cas.preprovisioned-scone5.3.0
        devices:
         - "${SGXDEVICE}"
        command: sh -c "SCONE_HASH=1 cas > /shared_test_vol/cas_hash.txt"
        volumes:
         - .:/shared_test_vol            
    build_and_sconify:
        image: ${SCONIFY_IMAGE}
        command: bash -c "/helper_scripts/alpine_wait_for_las_and_cas.sh && /sconification/sconify_all.sh"
        volumes:
            - ./sconification:/sconification
            - ./images:/images
            - ./helper_scripts:/helper_scripts
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - las
            - cas
    c_native:
        image: ${C_NATIVE_IMAGE}
    c_scone_binaryfs:
        image: ${C_TARGET_IMAGE}
        environment:
         - SCONE_VERSION=1
        devices:
         - "${SGXDEVICE}"
        depends_on:
            - las
            - cas
    cpp_native:
        image: ${CPP_NATIVE_IMAGE}
    cpp_scone_binaryfs:
        image: ${CPP_TARGET_IMAGE}
        environment:
         - SCONE_VERSION=1
        devices:
         - "${SGXDEVICE}"
        depends_on:
            - las
            - cas
    go_native:
        image: ${GO_NATIVE_IMAGE}
    go_scone_fspf:
        image: ${GO_TARGET_IMAGE_FSPF}
        environment:
         - SCONE_VERSION=1
        devices:
         - "${SGXDEVICE}"
        depends_on:
            - las
            - cas
    java_native:
        image: ${JAVA_NATIVE_IMAGE}
    java_scone_fspf:
        image: ${JAVA_TARGET_IMAGE_FSPF}
        environment:
         - SCONE_VERSION=1
        devices:
         - "${SGXDEVICE}"
        depends_on:
            - las
            - cas
    java8_native:
        image: ${JAVA8_NATIVE_IMAGE}
    java8_scone_fspf:
        image: ${JAVA8_TARGET_IMAGE_FSPF}
        environment:
         - SCONE_VERSION=1
        devices:
         - "${SGXDEVICE}"
        depends_on:
            - las
            - cas
    python_native:
        image: ${PYTHON_NATIVE_IMAGE}
    python_scone_binfs:
        image: ${PYTHON_TARGET_IMAGE_BINFS}
        environment:
         - SCONE_VERSION=1
        devices:
         - "${SGXDEVICE}"
        depends_on:
            - las
            - cas